const dummyData = [
  {
    id: 6992,
    createdOn: '2024-03-25 14:07:00.000+00',
    updatedOn: '2024-03-25 14:07:00.000+00',
    type: 'Dog Walk',
    appointmentDate: '2024-03-25',
    appointmentTime: 'Morning',
    client: {
      id: 10,
      firstName: 'Sophia',
      lastName: 'Moore',
      email: 'sophia.moore@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '789 Cedar St',
        city: 'Othertown',
        state: 'TX',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/45.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/45.jpg',
      },
    },
    employee: {
      id: 18,
      firstName: 'Mia',
      lastName: 'Wilson',
      email: 'mia.wilson@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Maple Ave',
        city: 'Anotherplace',
        state: 'CA',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/85.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
      },
    },
    pets: [
      {
        id: 22,
        type: 'Cat',
        name: 'Salem',
        breed: 'Sphynx',
        color: 'Black',
        age: 3,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Hairless breed, needs occasional bathing.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Anteater',
      },
      {
        id: 50,
        type: 'Cat',
        name: 'Luna',
        breed: 'Scottish Fold',
        color: 'Blue',
        age: 3,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Unique folded ears, enjoys quiet moments.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Sheep',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 12,
        type: 'Cat',
        name: 'Leo',
        breed: 'Scottish Fold',
        color: 'Cream',
        age: 1,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Unique folded ears, playful and curious.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hyena',
      },
    ],
  },
  {
    id: 5327,
    createdOn: '2024-03-04 23:01:00.000+00',
    updatedOn: '2024-03-04 23:01:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-03-04',
    appointmentTime: 'Evening',
    client: {
      id: 10,
      firstName: 'Sophia',
      lastName: 'Moore',
      email: 'sophia.moore@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '789 Cedar St',
        city: 'Othertown',
        state: 'TX',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/45.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/45.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 22,
        type: 'Cat',
        name: 'Salem',
        breed: 'Sphynx',
        color: 'Black',
        age: 3,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Hairless breed, needs occasional bathing.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Anteater',
      },
      {
        id: 50,
        type: 'Cat',
        name: 'Luna',
        breed: 'Scottish Fold',
        color: 'Blue',
        age: 3,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Unique folded ears, enjoys quiet moments.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Sheep',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 12,
        type: 'Cat',
        name: 'Leo',
        breed: 'Scottish Fold',
        color: 'Cream',
        age: 1,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Unique folded ears, playful and curious.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hyena',
      },
    ],
  },
  {
    id: 5930,
    createdOn: '2024-02-23 00:10:00.000+00',
    updatedOn: '2024-02-23 00:10:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-02-23',
    appointmentTime: 'Evening',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 18,
      firstName: 'Mia',
      lastName: 'Wilson',
      email: 'mia.wilson@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Maple Ave',
        city: 'Anotherplace',
        state: 'CA',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/85.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
      },
    },
    pets: [
      {
        id: 19,
        type: 'Dog',
        name: 'Zeus',
        breed: 'Great Dane',
        color: 'Fawn',
        age: 3,
        weight: '140lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Gentle giant, needs a spacious living area.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Ibex',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 39,
        type: 'Dog',
        name: 'Rusty',
        breed: 'Vizsla',
        color: 'Rust',
        age: 4,
        weight: '44lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Energetic and requires regular exercise.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Duck',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
    ],
  },
  {
    id: 24961,
    createdOn: '2024-03-26 21:03:00.000+00',
    updatedOn: '2024-03-26 21:03:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-03-26',
    appointmentTime: 'Afternoon',
    client: {
      id: 16,
      firstName: 'Ava',
      lastName: 'Martinez',
      email: 'ava.martinez@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Pine Ln',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/75.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/75.jpg',
      },
    },
    employee: {
      id: 21,
      firstName: 'Noah',
      lastName: 'Davis',
      email: 'noah.davis@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '101 Oak St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/3.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
      },
    },
    pets: [
      {
        id: 33,
        type: 'Dog',
        name: 'Lucy',
        breed: 'Beagle',
        color: 'Tri-color',
        age: 3,
        weight: '20lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Curious and good with families.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Turtle',
      },
      {
        id: 13,
        type: 'Dog',
        name: 'Riley',
        breed: 'Shetland Sheepdog',
        color: 'Sable',
        age: 4,
        weight: '18lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Loyal and good with families.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Rabbit',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
      {
        id: 14,
        type: 'Cat',
        name: 'Lily',
        breed: 'Ragdoll',
        color: 'Blue Bicolor',
        age: 2,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Gentle and affectionate, enjoys being held.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hippo',
      },
    ],
  },
  {
    id: 1677,
    createdOn: '2024-03-04 18:04:00.000+00',
    updatedOn: '2024-03-04 18:04:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-03-04',
    appointmentTime: 'Afternoon',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 21,
      firstName: 'Noah',
      lastName: 'Davis',
      email: 'noah.davis@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '101 Oak St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/3.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
      },
    },
    pets: [
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
    ],
  },
  {
    id: 20769,
    createdOn: '2024-02-12 15:13:00.000+00',
    updatedOn: '2024-02-12 15:13:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-02-12',
    appointmentTime: 'Afternoon',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 19,
        type: 'Dog',
        name: 'Zeus',
        breed: 'Great Dane',
        color: 'Fawn',
        age: 3,
        weight: '140lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Gentle giant, needs a spacious living area.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Ibex',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 39,
        type: 'Dog',
        name: 'Rusty',
        breed: 'Vizsla',
        color: 'Rust',
        age: 4,
        weight: '44lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Energetic and requires regular exercise.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Duck',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
    ],
  },
  {
    id: 14131,
    createdOn: '2024-03-16 16:07:00.000+00',
    updatedOn: '2024-03-16 16:07:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-03-16',
    appointmentTime: 'Morning',
    client: {
      id: 16,
      firstName: 'Ava',
      lastName: 'Martinez',
      email: 'ava.martinez@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Pine Ln',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/75.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/75.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 33,
        type: 'Dog',
        name: 'Lucy',
        breed: 'Beagle',
        color: 'Tri-color',
        age: 3,
        weight: '20lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Curious and good with families.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Turtle',
      },
      {
        id: 13,
        type: 'Dog',
        name: 'Riley',
        breed: 'Shetland Sheepdog',
        color: 'Sable',
        age: 4,
        weight: '18lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Loyal and good with families.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Rabbit',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
      {
        id: 14,
        type: 'Cat',
        name: 'Lily',
        breed: 'Ragdoll',
        color: 'Blue Bicolor',
        age: 2,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Gentle and affectionate, enjoys being held.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hippo',
      },
    ],
  },
  {
    id: 22919,
    createdOn: '2024-03-06 01:01:00.000+00',
    updatedOn: '2024-03-06 01:01:00.000+00',
    type: 'Dog Walk',
    appointmentDate: '2024-03-06',
    appointmentTime: 'Morning',
    client: {
      id: 14,
      firstName: 'Emma',
      lastName: 'Jones',
      email: 'emma.jones@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/65.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 8,
        type: 'Cat',
        name: 'Smokey',
        breed: 'Maine Coon',
        color: 'Gray',
        age: 3,
        weight: '15lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Fluffy and affectionate, enjoys grooming.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Chinchilla',
      },
    ],
  },
  {
    id: 24412,
    createdOn: '2024-02-13 22:10:00.000+00',
    updatedOn: '2024-02-13 22:10:00.000+00',
    type: 'Dog Walk',
    appointmentDate: '2024-02-13',
    appointmentTime: 'Evening',
    client: {
      id: 10,
      firstName: 'Sophia',
      lastName: 'Moore',
      email: 'sophia.moore@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '789 Cedar St',
        city: 'Othertown',
        state: 'TX',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/45.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/45.jpg',
      },
    },
    employee: {
      id: 24,
      firstName: 'Ella',
      lastName: 'Brown',
      email: 'ella.brown@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/2.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
      },
    },
    pets: [
      {
        id: 22,
        type: 'Cat',
        name: 'Salem',
        breed: 'Sphynx',
        color: 'Black',
        age: 3,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Hairless breed, needs occasional bathing.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Anteater',
      },
      {
        id: 50,
        type: 'Cat',
        name: 'Luna',
        breed: 'Scottish Fold',
        color: 'Blue',
        age: 3,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Unique folded ears, enjoys quiet moments.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Sheep',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 12,
        type: 'Cat',
        name: 'Leo',
        breed: 'Scottish Fold',
        color: 'Cream',
        age: 1,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Unique folded ears, playful and curious.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hyena',
      },
    ],
  },
  {
    id: 26665,
    createdOn: '2024-03-17 19:11:00.000+00',
    updatedOn: '2024-03-17 19:11:00.000+00',
    type: 'Dog Walk',
    appointmentDate: '2024-03-17',
    appointmentTime: 'Evening',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 21,
      firstName: 'Noah',
      lastName: 'Davis',
      email: 'noah.davis@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '101 Oak St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/3.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
      },
    },
    pets: [
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
    ],
  },
  {
    id: 7583,
    createdOn: '2024-02-25 15:05:00.000+00',
    updatedOn: '2024-02-25 15:05:00.000+00',
    type: 'Dog Walk',
    appointmentDate: '2024-02-25',
    appointmentTime: 'Evening',
    client: {
      id: 14,
      firstName: 'Emma',
      lastName: 'Jones',
      email: 'emma.jones@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/65.jpg',
      },
    },
    employee: {
      id: 9,
      firstName: 'William',
      lastName: 'Jones',
      email: 'william.jones@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '222 Oak St',
        city: 'Anyplace',
        state: 'CA',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/45.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/45.jpg',
      },
    },
    pets: [
      {
        id: 8,
        type: 'Cat',
        name: 'Smokey',
        breed: 'Maine Coon',
        color: 'Gray',
        age: 3,
        weight: '15lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Fluffy and affectionate, enjoys grooming.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Chinchilla',
      },
    ],
  },
  {
    id: 19317,
    createdOn: '2024-02-14 16:14:00.000+00',
    updatedOn: '2024-02-14 16:14:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-02-14',
    appointmentTime: 'Evening',
    client: {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/35.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/35.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 7,
        type: 'Dog',
        name: 'Max',
        breed: 'Golden Retriever',
        color: 'Cream',
        age: 5,
        weight: '70lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Gentle and friendly, great with kids.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Alligator',
      },
      {
        id: 5,
        type: 'Dog',
        name: 'Luna',
        breed: 'Husky',
        color: 'Gray and White',
        age: 2,
        weight: '44lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Energetic and playful, needs regular outdoor activities.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Capybara',
      },
    ],
  },
  {
    id: 30834,
    createdOn: '2024-03-19 01:08:00.000+00',
    updatedOn: '2024-03-19 01:08:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-03-19',
    appointmentTime: 'Afternoon',
    client: {
      id: 19,
      firstName: 'Jackson',
      lastName: 'Garcia',
      email: 'jackson.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Cedar St',
        city: 'Everywhere',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/95.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/95.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 46,
        type: 'Cat',
        name: 'Casper',
        breed: 'Ragamuffin',
        color: 'White',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Fluffy and friendly, enjoys being brushed.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Elephant',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
      {
        id: 40,
        type: 'Cat',
        name: 'Apollo',
        breed: 'Birman',
        color: 'Blue',
        age: 2,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Graceful and enjoys quiet environments.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Crow',
      },
      {
        id: 47,
        type: 'Dog',
        name: 'Zara',
        breed: 'Australian Shepherd',
        color: 'Merle',
        age: 3,
        weight: '44lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and requires mental stimulation.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Llama',
      },
    ],
  },
  {
    id: 8153,
    createdOn: '2024-02-26 22:08:00.000+00',
    updatedOn: '2024-02-26 22:08:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-02-26',
    appointmentTime: 'Morning',
    client: {
      id: 10,
      firstName: 'Sophia',
      lastName: 'Moore',
      email: 'sophia.moore@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '789 Cedar St',
        city: 'Othertown',
        state: 'TX',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/45.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/45.jpg',
      },
    },
    employee: {
      id: 18,
      firstName: 'Mia',
      lastName: 'Wilson',
      email: 'mia.wilson@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Maple Ave',
        city: 'Anotherplace',
        state: 'CA',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/85.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
      },
    },
    pets: [
      {
        id: 22,
        type: 'Cat',
        name: 'Salem',
        breed: 'Sphynx',
        color: 'Black',
        age: 3,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Hairless breed, needs occasional bathing.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Anteater',
      },
      {
        id: 50,
        type: 'Cat',
        name: 'Luna',
        breed: 'Scottish Fold',
        color: 'Blue',
        age: 3,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Unique folded ears, enjoys quiet moments.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Sheep',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 12,
        type: 'Cat',
        name: 'Leo',
        breed: 'Scottish Fold',
        color: 'Cream',
        age: 1,
        weight: '8lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Unique folded ears, playful and curious.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hyena',
      },
    ],
  },
  {
    id: 31277,
    createdOn: '2024-03-29 19:02:00.000+00',
    updatedOn: '2024-03-29 19:02:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-03-29',
    appointmentTime: 'Afternoon',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 18,
      firstName: 'Mia',
      lastName: 'Wilson',
      email: 'mia.wilson@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Maple Ave',
        city: 'Anotherplace',
        state: 'CA',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/85.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
      },
    },
    pets: [
      {
        id: 19,
        type: 'Dog',
        name: 'Zeus',
        breed: 'Great Dane',
        color: 'Fawn',
        age: 3,
        weight: '140lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Gentle giant, needs a spacious living area.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Ibex',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 39,
        type: 'Dog',
        name: 'Rusty',
        breed: 'Vizsla',
        color: 'Rust',
        age: 4,
        weight: '44lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Energetic and requires regular exercise.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Duck',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
    ],
  },
  {
    id: 24593,
    createdOn: '2024-03-08 00:11:00.000+00',
    updatedOn: '2024-03-08 00:11:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-03-08',
    appointmentTime: 'Evening',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 24,
      firstName: 'Ella',
      lastName: 'Brown',
      email: 'ella.brown@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/2.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
      },
    },
    pets: [
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
    ],
  },
  {
    id: 10539,
    createdOn: '2024-02-26 17:05:00.000+00',
    updatedOn: '2024-02-26 17:05:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-02-26',
    appointmentTime: 'Afternoon',
    client: {
      id: 14,
      firstName: 'Emma',
      lastName: 'Jones',
      email: 'emma.jones@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/65.jpg',
      },
    },
    employee: {
      id: 24,
      firstName: 'Ella',
      lastName: 'Brown',
      email: 'ella.brown@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/2.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
      },
    },
    pets: [
      {
        id: 8,
        type: 'Cat',
        name: 'Smokey',
        breed: 'Maine Coon',
        color: 'Gray',
        age: 3,
        weight: '15lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Fluffy and affectionate, enjoys grooming.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Chinchilla',
      },
    ],
  },
  {
    id: 32731,
    createdOn: '2024-03-30 14:14:00.000+00',
    updatedOn: '2024-03-30 14:14:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-03-30',
    appointmentTime: 'Evening',
    client: {
      id: 7,
      firstName: 'Daniel',
      lastName: 'Brown',
      email: 'daniel.brown@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Anothertown',
        state: 'TX',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/5.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/5.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 24,
        type: 'Cat',
        name: 'Shadow',
        breed: 'Norwegian Forest Cat',
        color: 'Gray',
        age: 4,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Fluffy and enjoys climbing, good hunter.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Alligator',
      },
      {
        id: 14,
        type: 'Cat',
        name: 'Lily',
        breed: 'Ragdoll',
        color: 'Blue Bicolor',
        age: 2,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Gentle and affectionate, enjoys being held.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hippo',
      },
      {
        id: 27,
        type: 'Dog',
        name: 'Teddy',
        breed: 'Pomeranian',
        color: 'Orange',
        age: 3,
        weight: '5lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Fluffy and energetic, requires regular grooming.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Liger',
      },
    ],
  },
  {
    id: 13404,
    createdOn: '2024-03-09 23:00:00.000+00',
    updatedOn: '2024-03-09 23:00:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-03-09',
    appointmentTime: 'Morning',
    client: {
      id: 7,
      firstName: 'Daniel',
      lastName: 'Brown',
      email: 'daniel.brown@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Anothertown',
        state: 'TX',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/5.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/5.jpg',
      },
    },
    employee: {
      id: 11,
      firstName: 'Matthew',
      lastName: 'Garcia',
      email: 'matthew.garcia@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '456 Pine Ln',
        city: 'Sometown',
        state: 'CA',
        zipcode: '98765',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/55.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
      },
    },
    pets: [
      {
        id: 24,
        type: 'Cat',
        name: 'Shadow',
        breed: 'Norwegian Forest Cat',
        color: 'Gray',
        age: 4,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Fluffy and enjoys climbing, good hunter.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Alligator',
      },
      {
        id: 14,
        type: 'Cat',
        name: 'Lily',
        breed: 'Ragdoll',
        color: 'Blue Bicolor',
        age: 2,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Gentle and affectionate, enjoys being held.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hippo',
      },
      {
        id: 27,
        type: 'Dog',
        name: 'Teddy',
        breed: 'Pomeranian',
        color: 'Orange',
        age: 3,
        weight: '5lbs',
        specialNeeds: {
          medical: true,
          dietary: true,
        },
        notes: 'Fluffy and energetic, requires regular grooming.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Liger',
      },
    ],
  },
  {
    id: 24089,
    createdOn: '2024-02-17 00:09:00.000+00',
    updatedOn: '2024-02-17 00:09:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-02-17',
    appointmentTime: 'Evening',
    client: {
      id: 8,
      firstName: 'Olivia',
      lastName: 'Wilson',
      email: 'olivia.wilson@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '101 Maple Ave',
        city: 'Everytown',
        state: 'WA',
        zipcode: '24680',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/5.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/5.jpg',
      },
    },
    employee: {
      id: 24,
      firstName: 'Ella',
      lastName: 'Brown',
      email: 'ella.brown@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/2.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
      },
    },
    pets: [
      {
        id: 50,
        type: 'Cat',
        name: 'Luna',
        breed: 'Scottish Fold',
        color: 'Blue',
        age: 3,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Unique folded ears, enjoys quiet moments.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Sheep',
      },
      {
        id: 7,
        type: 'Dog',
        name: 'Max',
        breed: 'Golden Retriever',
        color: 'Cream',
        age: 5,
        weight: '70lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Gentle and friendly, great with kids.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Alligator',
      },
      {
        id: 15,
        type: 'Dog',
        name: 'Oliver',
        breed: 'Cavalier King Charles Spaniel',
        color: 'Blenheim',
        age: 1,
        weight: '13lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Friendly and good with children.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Chipmunk',
      },
    ],
  },
  {
    id: 27493,
    createdOn: '2024-03-31 00:03:00.000+00',
    updatedOn: '2024-03-31 00:03:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-03-31',
    appointmentTime: 'Morning',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 24,
      firstName: 'Ella',
      lastName: 'Brown',
      email: 'ella.brown@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Cedar St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/2.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
      },
    },
    pets: [
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
    ],
  },
  {
    id: 20230,
    createdOn: '2024-02-29 00:12:00.000+00',
    updatedOn: '2024-02-29 00:12:00.000+00',
    type: 'Home Visit',
    appointmentDate: '2024-02-29',
    appointmentTime: 'Evening',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 18,
      firstName: 'Mia',
      lastName: 'Wilson',
      email: 'mia.wilson@example.com',
      phone: '+1 (555) 876-5432',
      location: {
        address: '222 Maple Ave',
        city: 'Anotherplace',
        state: 'CA',
        zipcode: '54321',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/85.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
      },
    },
    pets: [
      {
        id: 19,
        type: 'Dog',
        name: 'Zeus',
        breed: 'Great Dane',
        color: 'Fawn',
        age: 3,
        weight: '140lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Gentle giant, needs a spacious living area.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Ibex',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 39,
        type: 'Dog',
        name: 'Rusty',
        breed: 'Vizsla',
        color: 'Rust',
        age: 4,
        weight: '44lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Energetic and requires regular exercise.',
        indoorOnly: false,
        spayedNeutered: false,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Duck',
      },
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
    ],
  },
  {
    id: 11808,
    createdOn: '2024-02-08 23:06:00.000+00',
    updatedOn: '2024-02-08 23:06:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-02-08',
    appointmentTime: 'Morning',
    client: {
      id: 16,
      firstName: 'Ava',
      lastName: 'Martinez',
      email: 'ava.martinez@example.com',
      phone: '+1 (555) 789-0123',
      location: {
        address: '789 Pine Ln',
        city: 'Sometown',
        state: 'NY',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/women/75.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/women/75.jpg',
      },
    },
    employee: {
      id: 9,
      firstName: 'William',
      lastName: 'Jones',
      email: 'william.jones@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '222 Oak St',
        city: 'Anyplace',
        state: 'CA',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/45.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/45.jpg',
      },
    },
    pets: [
      {
        id: 33,
        type: 'Dog',
        name: 'Lucy',
        breed: 'Beagle',
        color: 'Tri-color',
        age: 3,
        weight: '20lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Curious and good with families.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Turtle',
      },
      {
        id: 13,
        type: 'Dog',
        name: 'Riley',
        breed: 'Shetland Sheepdog',
        color: 'Sable',
        age: 4,
        weight: '18lbs',
        specialNeeds: {
          medical: true,
          dietary: false,
        },
        notes: 'Loyal and good with families.',
        indoorOnly: false,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Rabbit',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
      {
        id: 14,
        type: 'Cat',
        name: 'Lily',
        breed: 'Ragdoll',
        color: 'Blue Bicolor',
        age: 2,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Gentle and affectionate, enjoys being held.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Hippo',
      },
    ],
  },
  {
    id: 28946,
    createdOn: '2024-03-12 00:00:00.000+00',
    updatedOn: '2024-03-12 00:00:00.000+00',
    type: 'Dog Walk',
    appointmentDate: '2024-03-12',
    appointmentTime: 'Morning',
    client: {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/35.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/35.jpg',
      },
    },
    employee: {
      id: 21,
      firstName: 'Noah',
      lastName: 'Davis',
      email: 'noah.davis@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '101 Oak St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/3.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
      },
    },
    pets: [
      {
        id: 18,
        type: 'Cat',
        name: 'Simba',
        breed: 'Bengal',
        color: 'Spotted Rosetted',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Playful and enjoys interactive toys.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url:
          'https://anonymous-animals.azurewebsites.net/animal/Chinchilla',
      },
    ],
  },
  {
    id: 6684,
    createdOn: '2024-03-01 21:09:00.000+00',
    updatedOn: '2024-03-01 21:09:00.000+00',
    type: 'Boarding',
    appointmentDate: '2024-03-01',
    appointmentTime: 'Morning',
    client: {
      id: 13,
      firstName: 'James',
      lastName: 'Smith',
      email: 'james.smith@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '789 Maple Ave',
        city: 'Othertown',
        state: 'TX',
        zipcode: '67890',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/65.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    employee: {
      id: 21,
      firstName: 'Noah',
      lastName: 'Davis',
      email: 'noah.davis@example.com',
      phone: '+1 (555) 234-5678',
      location: {
        address: '101 Oak St',
        city: 'Sometown',
        state: 'NY',
        zipcode: '12345',
        country: 'USA',
      },
      picture: {
        avatar_url: 'https://randomuser.me/api/portraits/men/3.jpg',
        thumb_url: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
      },
    },
    pets: [
      {
        id: 36,
        type: 'Cat',
        name: 'Loki',
        breed: 'Siamese',
        color: 'Chocolate Point',
        age: 4,
        weight: '11lbs',
        specialNeeds: {
          medical: false,
          dietary: false,
        },
        notes: 'Vocal and enjoys human interaction.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Skunk',
      },
      {
        id: 35,
        type: 'Dog',
        name: 'Bailey',
        breed: 'Miniature Schnauzer',
        color: 'Salt and Pepper',
        age: 2,
        weight: '15lbs',
        specialNeeds: {
          medical: false,
          dietary: true,
        },
        notes: 'Intelligent and good with training.',
        indoorOnly: true,
        spayedNeutered: true,
        image_url: 'https://anonymous-animals.azurewebsites.net/animal/Dolphin',
      },
    ],
  },
];

export default dummyData;
